import { Rubik, Space_Grotesk } from "next/font/google";
import './globals.css'
import {Header} from "@/components/Header";
import NextTopLoader from "nextjs-toploader";
import {hasLocale, NextIntlClientProvider, useMessages} from "next-intl";
import {ThemeProvider} from "next-themes";
import {notFound} from "next/navigation";
import {routing} from "@/i18n/routing";

const space_grotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const rubik = Rubik({
  variable: "--rubik",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const {locale} = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}
          dir={locale === 'ar' || locale === 'fa' ? 'rtl' : 'ltr'}
          className={`${space_grotesk.variable} ${rubik.variable} scroll-smooth`}
          suppressHydrationWarning>
      <body>
      <ThemeProvider
        enableSystem
        attribute='class'
        defaultTheme='light'
        themes={[
          'light',
          'dark',
          'instagram',
          'facebook',
          'discord',
          'netflix',
          'twilight',
          'reddit'
        ]}
      >
        <NextIntlClientProvider>
          <NextTopLoader
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            easing='ease'
            speed={200}
            shadow='0 0 10px #2299DD,0 0 5px #2299DD'
            color='var(--primary)'
            showSpinner={false}
          />
          <Header locale={locale} />
          <main className='mx-auto max-w-screen-2xl'>{children}</main>
        </NextIntlClientProvider>
      </ThemeProvider>
      </body>
    </html>
  );
}
